version: 0.2

env:
  variables:
    TF_ROOT: '${CODEBUILD_SRC_DIR}'

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - gitlab-terraform init
      - gitlab-terraform validate
      - gitlab-terraform plan
      - gitlab-terraform apply
      #- gitlab-terraform destroy

cache:
  paths:
    - '${CODEBUILD_SRC_DIR}/.terraform'
